version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - minha_rede

volumes:
  db_data:

networks:
  minha_rede:
    driver: bridge
