
services:
  web:
    build: .
    container_name: fastapi_container
    ports:
      - "80:80"
    environment:
      - DB_HOST=mariadb_container
      - MYSQL_DATABASE=seu_banco
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senha_root
    volumes:
      - .:/app
    networks: 
      - shared_network 
      
networks: 
  shared_network: 
    external: true