
services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: seu_banco
      MYSQL_USER: root
      MYSQL_PASSWORD: senha_root
      TZ: UTC 
      MARIADB_COLLATION_SERVER: utf8mb4_general_ci # Configurar colação aqui
    ports:
      - "3306:3306"
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: fastapi_container
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=mariadb_container
      - DB_NAME=seu_banco
      - DB_USER=root
      - DB_PASSWORD=senha_root
    volumes:
      - .:/app

volumes:
  db_data:
